apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-cluster1
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: test-cert-manager
  destination:
    server: https://192.168.58.2:8443
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
