apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-cluster1
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.2
    helm:
      releaseName: test-postgresql
  destination:
    server: https://192.168.58.2:8443
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true