---
kind: Application
metadata:
  name: mongodb-abc-xyz-k8s-test-87654321
spec:
  source:
    targetRevision: 13.9.0
    helm:
      releaseName: test-mongodb
  destination:
    server: https://192.168.49.2:8443
    namespace: mongo
---
kind: Application
metadata:
  name: postgresql-abc-xyz-k8s-test-87654321
spec:
  source:
    targetRevision: 12.2.2
    helm:
      releaseName: test-postgresql
  destination:
    server: https://192.168.49.2:8443
    namespace: postgresql
---
kind: Application
metadata:
  name: sealed-secret-def-rel-k8s-dev-01268492
spec:
  source:
    targetRevision: 2.8.0
    helm:
      releaseName: test-sealed
  destination:
    server: https://192.168.49.2:8443
    namespace: secrets
---