---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  source:
    targetRevision: 13.9.0
    helm:
      releaseName: test-mongodb
  destination:
    server: https://192.168.49.2:8443
    namespace: mongo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  source:
    targetRevision: 12.2.2
    helm:
      releaseName: test-postgresql
  destination:
    server: https://192.168.49.2:8443
    namespace: postgresql
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: argocd
spec:
  source:
    targetRevision: 2.8.0
    helm:
      releaseName: test-sealed
  destination:
    server: https://192.168.49.2:8443
    namespace: secrets
---