---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-abc-xyz-k8s-test-87654321
  namespace: argocd
spec:
  project: default
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.9.0
    helm:
      releaseName: test-mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-abc-xyz-k8s-test-87654321
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.2
    helm:
      releaseName: test-postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-def-rel-k8s-dev-01268492
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.6
    helm:
      releaseName: test-sealed
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---