apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-def-rel-k8s-dev-01268492
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.6
    helm:
      releaseName: test-sealed
  destination:
    server: https://192.168.49.2:8443
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true