apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-in-cluster
  namespace: argocd
spec:
  project: default
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.9.0
    helm:
      releaseName: test-mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true