#This application will keep watching for any application set files that comes in appset folder.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-sets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msm17b019/argocd-test.git
    targetRevision: main
    path: config/appset
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
