# The secret template for adding cluster in ArgoCD.

apiVersion: v1
kind: Secret
metadata:
  name: cluster1-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd.argoproj.io/cluster-name: <cluster_name>
  namespace: argocd
type: Opaque
stringData:
  name: cluster1
  server: 
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData": "",
        "certData": "",
        "keyData": ""
      }
    }
