apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-specific
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-app-of-apps'
    spec:
      project: default
      source:
        repoURL: https://github.com/msm17b019/argocd-test.git
        targetRevision: main
        path: config/{{name}}/template
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true