apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/msm17b019/argocd-test.git
              revision: main
              directories:
              - files: config/environment/clusters/*/apps/*/config.json
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  argocd.argoproj.io/cluster-name: '{{path[3]}}'
  template:
    metadata:
      name: '{{path[3]}}-app-of-apps'
    spec:
      project: default
      source:
        chart: {{chart.name}}
        repoURL: {{chart.repoUrl}}
        targetRevision: {{chart.version}}
        helm:
          releaseName: sealed-secrets
          valueFiles:
          - config/environment/clusters/{{path[3]}}/apps/path{{[5]}}/values.yaml
      destination:
        server: {{server}}
        namespace: {{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true