apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - app: vault

    - matrix:
        generators:
          - git:
              repoURL: https://github.com/msm17b019/argocd-test.git
              revision: main
              directories:
              - path: config/environment/clusters/*
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  argocd.argoproj.io/cluster-name: '{{path.basename}}'
  template:
    metadata:
      name: '{{path.basename}}-{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/msm17b019/argocd-test
        targetRevision: main
        path: "config/environment/clusters/{{path.basename}}/{{app}}"
      destination:
        server: {{server}}
        namespace: {{app}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true