apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-minikube
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.29
    helm:
      releaseName: test-nginx
  destination:
    server: https://192.168.49.2:8443
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
