apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - "../../../base/"
  
patchesStrategicMerge:
  - "override.yaml"

nameSuffix: "-abc-xyz-k8s-test-87654321"