apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mongodb
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: minikube
        url: https://192.168.49.2:8443
      - cluster: cluster1
        url : https://192.168.58.2:8443
  template:
    metadata:
      name: '{{cluster}}-mongodb'
    spec:
      project: default
      source:
        chart: mongodb
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 13.9.0
        helm:
          releaseName: test-mongodb
      destination:
        server: '{{url}}'
        namespace: mongodb
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
